### ISSUE TITLE
TODO: Add fuzzing

### ISSUE THREAD

**Issue by joshdavham** [open-spaced-repetition/anki-sm-2#1]
This package currently does not have fuzzing like the official Anki implementation: https://github.com/ankitects/anki/blob/main/rslib/src/scheduler/states/fuzz.rs

**Comment by joshdavham** [comment]
To anyone comfortable with Rust and Anki fuzzing, your help adding fuzzing to this package would be greatly appreciated!

**Comment by L-M-Sherlock** [comment]
You can refer to this:

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/38e79df5a7f763517adae6c3b2cdc9e5458a8b07/utils.py#L120-L153
